shoponline/src/mycart/urls.py
'''
Created on Nov 12, 2017

@author: lhdat
'''
from mycart import views
from django.conf.urls import url

app_name = 'mycart'

urlpatterns = [
    url(r'^cart_add/(\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_remove/(\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^cart_detail/$', views.cart_detail, name='cart_detail'),
]

shoponline/src/mystore/urls.py
'''
Created on Nov 12, 2017

@author: hv
'''
from django.conf.urls import url
from mystore import views

app_name = 'mystore'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^product_detail/(\d+)/$', views.product_detail, name='product_detail'),
    url(r'^readcookie/$', views.read_cookie, name='readcookie'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^create/', views.order_create, name='ordercreate'),
]

shoponline/src/shoponline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from shoponline import views, settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.index, name='index'),
    url(r'^mystore/', include('mystore.urls')),
    url(r'^mycart/', include('mycart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoponline/src/mycart/forms.py
'''
Created on Nov 12, 2017

@author: lhdat
'''
from django import forms
from builtins import int

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CardAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label='quantity', choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, widget=forms.HiddenInput)

shoponline/src/mycart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .cart import Cart
from mystore.models import Product
from .forms import CardAddProductForm

# Create your views here.


@require_POST
def cart_add(request, product_id=None):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CardAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
        print(cart)
        return redirect('mycart:cart_detail')


def cart_remove(request, product_id=None):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('mycart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CardAddProductForm(initial={'quantity': item['quantity'], 'update': True})
        
    return render(request, 'mycart/cart_detail.html', context={'cart':cart})
    

shoponline/src/templates/mycart/cart_detail.html
<!DOCTYPE html>

{% extends "mystore/base.html" %}

{% block body_block %}
    <h2>cart details</h2>
    <table class="table">
    <thead class="danger">
    <th>product</th>
    <th>product name</th>
    <th>quantity</th>
    <th>price ($)</th>
    <th>amount ($)</th>
    <th>delete</th>
    </thead>
    <tbody>
        {% for item in cart %}
        <tr>
            <td><a href="{% url 'mystore:product_detail' item.product.pk %}"><img src="{{item.product.image.url}}" /></a></td>
            <td>{{item.product.name}}</td>
            <td>
            <form action="{% url 'mycart:cart_add' item.product.pk %}" method="post">
                {{item.update_quantity_form.quantity}}
                {{item.update_quantity_form.update}}
                <input type="submit" class="btn btn-primary" value="update" />
                {% csrf_token %}
            </form>
            </td>
            <td>{{item.fee}}</td>
            <td>{{item.total_fee}}</td>
            <td><a href="{% url 'mycart:cart_remove' item.product.pk %}">delete</a></td>
        </tr>
        {% endfor %}
        <tr class="total">
        <td colspan="4"></td>
        <td class="num">total: {{cart.get_total_fee}} $</td>
        </tr>
    </tbody>
</table>
<div class="text-right">
	<a href="{% url 'mystore:index' %}" class="button light">Order</a>
	<hr>
	<a href="{% url 'mystore:ordercreate' %}" class="btn btn-primary">Payment</a>
	<br>
</div>

{% endblock %}