shoponline/src/mycart/urls.py
'''
Created on Nov 12, 2017

@author: lhdat
'''
from mycart import views
from django.conf.urls import url

app_name = 'mycart'

urlpatterns = [
    url(r'^cart_add/(\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart_remove/(\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^cart_detail/$', views.cart_detail, name='cart_detail'),
]

shoponline/src/mystore/urls.py
'''
Created on Nov 12, 2017

@author: hv
'''
from django.conf.urls import url
from mystore import views

app_name = 'mystore'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^product_detail/(\d+)/$', views.product_detail, name='product_detail'),
    url(r'^readcookie/$', views.read_cookie, name='readcookie'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^create/', views.order_create, name='ordercreate'),
]

shoponline/src/shoponline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from shoponline import views, settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.index, name='index'),
    url(r'^mystore/', include('mystore.urls')),
    url(r'^mycart/', include('mycart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoponline/src/mystore/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=264, unique=True)
    fee = models.FloatField()
    description = models.TextField()
    image = models.ImageField(upload_to="images/")
    
    def __str__(self):
        return str(self.name)
    

class UserProfileInfo(models.Model):
    # create relationship from this class to User
    user = models.OneToOneField(User, on_delete=False)
    # add any more attribute you want
    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to="images/", blank=True)
    
    def __str__(self):
        return self.user.username

    
class Order(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    
    class Meta:
        ordering = ('-created',)   
        
    def __str__(self):
        return 'Order{}'.format(self.id)
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=False, related_name='items')
    product = models.ForeignKey(Product, on_delete=False, related_name='item')
    price = models.FloatField()
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity
    

shoponline/src/mystore/forms.py
'''
Created on Nov 18, 2017

@author: hv
'''
from django import forms
from django.contrib.auth.models import User
from mystore.models import UserProfileInfo, Order


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

        
class UserProfileInfoForm(forms.ModelForm):
    # porfolio = forms.URLField(required = False)
    picture = forms.ImageField(required=False)
    
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio', 'picture')

        
class OrderCreateForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['firstName', 'lastName', 'email', 'address']

        
def clear(self):
    self.cart = {}
    self.save()

shoponline/src/mystore/views.py
from django.shortcuts import render

# Create your views here.
from mystore.models import Product, OrderItem
from _datetime import datetime
from django.http.response import HttpResponse
from mycart import forms
from mystore.forms import  UserForm, UserProfileInfoForm, OrderCreateForm

from mycart.cart import Cart
import profile
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def index(request):
    date1 = datetime.now()
    value = request.COOKIES.get('last_visit', \
                                date1.strftime('%d-%m-%Y %H:%M:%S'))
    pro_list = Product.objects.order_by('name')
    pro_dict = {'products' : pro_list, 'last_visit' : value}
    response = render(request, "mystore/index.html", context=pro_dict)
    response.set_cookie('last_visit', \
                        date1.strftime('%d-%m-%Y %H:%M:%S'))
    return response


def product_detail(request, id=None):
    product = Product.objects.get(pk=id)
    cart_product_form = forms.CardAddProductForm()
    return render(request, 'mystore/product_detail.html', \
                  context={'product':product, \
                             'cart_product_form':cart_product_form})


def read_cookie(request):
    value = request.COOKIES.get('last_visit')
    text = "<h3>The last time to visit this page is %s</h3>" % value
    return HttpResponse(text)


def register(request):
    registered = False
    if request.method == 'POST':
        form_user = UserForm(data=request.POST)
        form_por = UserProfileInfoForm(data=request.POST)
        if form_user.is_valid() and form_por.is_valid():
            user = form_user.save(commit=False)
            user.set_password(user.password)
            user.save()
            
            profile = form_por.save(commit=False)
            profile.user = user
            
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                
            profile.save()
            
            registered = True
            
        else:
            print(form_user.error, form_por.error)
    else:
        form_user = UserForm()
        form_por = UserProfileInfoForm()
        
    return render(request, 'mystore/registration.html', \
                  context={'user_form': form_user, \
                             'profile_form': form_por, \
                             'registered': registered})


def user_login(request):
    if request.method == 'POST':
        uname = request.POST.get('username')
        passwd = request.POST.get('password')
        user = authenticate(username=uname, password=passwd)
        if user:
            if user.is_active:
                login(request, user)
                # clean cart
                cart = Cart(request)
                cart.clear()
                
                result = 'Welcome ' + uname
                cart = Cart(request)
                cart.user = uname
                return render(request, 'mystore/index.html', \
                              context={'result': result})
        else:
            print('login failed')
            login_result = 'username and password is invalid'
            return render(request, 'mystore/login.html', \
                          context={'login_result': login_result})
    else:
        return render(request, 'mystore/login.html')

    
@login_required
def user_logout(request):
    logout(request)
    # clean cart
    cart = Cart(request)
    cart.clear()
    
    result = 'You already log out . You should log in'
    return render(request, 'mystore/index.html', \
                  context={'result': result})


def order_create(request):
    cart = Cart(request)
    form = OrderCreateForm()
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, \
                                         product=item['product'], \
                                         price=item['fee'], \
                                         quantity=item['quantity'])
            
            cart.clear()
            return render(request, 'mystore/created.html', \
                          context={'order': order})
    else:
        form = OrderCreateForm()
        return render(request, 'mystore/create.html', \
                      context={'form': form})

shoponline/src/templates/mystore/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bookstore</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet" />

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'mystore:index' %}">Bookstore<img src="{% static 'images/logo.jpg' %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'mystore:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mycart:cart_detail' %}"><img src="{% static 'images/cart.png' %}" /></a>
            </li>
            <li class="cart active">
                {% if cart %}
                    <a class="nav-link" href="{% url 'mycart:cart_detail' %}">
                    cart has {{cart|length}} products, {{cart.get_total_fee}} $
                    </a>
                {% endif %}
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mystore:register' %}">Register</a>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mystore:login' %}">Login</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mystore:logout' %}">Logout</a>
            </li>
            {% endif %}
            <li class="nav-item active">
            {% if user.is_authenticated %}
              <a class="nav-link" href="#">userid : {{user.username}}</a>
            {% endif %}
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">{{last_visit}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mystore:readcookie' %}">read cookie</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-3">
        <h3 class="display-3">Bookstore online</h3>
        <a href="#" class="btn btn-primary btn-lg">Call to order</a>
        <div class="carousel-inner">
	    <div class="item">
	      <img src="{% static 'images/banner2.jpg' %}" alt="banner3" style="width:100%;">
	    </div>
	  </div>
      </header>

    {% block body_block %}
      
    {% endblock %}
      
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Bookstore online 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  </body>

</html>

shoponline/src/templates/mystore/create.html
{% extends "mystore/base.html" %}

{% block body_block %}
<div class="row text-center"></div>
<table align="center">
<tr>
<td valign="top" width='50%'>
<h4>Customer</h4>
<form action="." method="post">
<table>
{% for field in form %}
<tr>
<td>{{field.label}} </td>
 <td>{{field}}</td>
 </tr>
{% endfor %}
<tr>
<td colspan="2" align="center">
<p><input type ="submit" value = "Payment"
class="btn btn-primary"></p>
</td>
</tr>
</table>
{% csrf_token %}
</form>
<br>
</td>
<td valign="top">
<h4>Detailed Order</h4><i>(payment on delivery)</i>
<ul>
{% for item in cart %}
<li>
{{item.quantity}} x
{{item.product.name}} = <span>{{item.total_fee}}</span>
</li>
{% endfor %}
</ul>
<ul>Total: {{cart.get_total_fee}} $</ul>
</td>
</tr>
</table>
</div>
{% endblock %}

shoponline/src/templates/mystore/created.html
{% extends "mystore/base.html" %}
{% block body_block %}
<div class="row text-center"><h5><font color="blue">Payment Completed</font></h5><br></div>
<div class="row text-center">
<p><font color="blue">Your order is made payment successful with id order:
<strong>{{order.id}}</strong></font></p>
</div>
{% endblock %}

shoponline/src/templates/mystore/index.html
{% extends "mystore/base.html" %}

{% block body_block %}
<!-- Page Features -->
     <div class="row text-center"><font color="blue">{{result}}</font></div>
<div class="row text-center">
	 <!-- Page Features -->
      <div class="row text-center">
		{% if products %}
		{% for value in products %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <img class="card-img-top" src="{{value.image.url}}" alt="{{value.name}}">
            <div class="card-body">
              <h4 class="card-title">{{value.name}}</h4>
              <p class="card-text">{{value.description}}<br>{{value.fee}}$</p>
            </div>
            <div class="card-footer">
              <a href="{% url 'mystore:product_detail' value.pk %}" class="btn btn-primary">Find Out More!</a>
            </div>
          </div>
        </div>

        {% endfor %}
		{% endif %}
		</div>
      </div>
      <!-- /.row -->
{% endblock %}

shoponline/src/templates/mystore/login.html
{% extends "mystore/base.html" %}

{% block body_block %}
<div class="row text-center">
	 <!-- Page Features -->
	 <div class="row text-center"><font color="red">{{login_result}}</font></div>
      <div class="text-center">
     	<h3>Log in</h3><br>
      		<form method="post" action="{% url 'mystore:login' %}">
      			<table>
      				<tr>
      					<td><lable for="username">Username:</lable></td>
      					<td><input type="text" name="username" placeholder="enter username" /></td>
      				</tr>
      				<tr>
      					<td><lable for="password">Password:</lable></td>
      					<td><input type="password" name="password" placeholder="enter password" /></td>
      				</tr>
      				<tr>
      					<td colspan="2" align="center"><input type="submit" class="btn btn-primary" value="Login" /></td>
      				</tr>
      			</table>
      		{% csrf_token %}
      		</form>
      </div>
      </div>
      <!-- /.row -->
{% endblock %}

shoponline/src/templates/mystore/product_detail.html
<!DOCTYPE html>

{% extends "mystore/base.html" %}

{% block body_block %}
	 <!-- Page Features -->
      <div class="row text-center">
		{% if product %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}">
            <div class="card-body">
              <h4 class="card-title">{{product.name}}</h4>
              <p class="card-text">{{product.description}}<br>{{product.fee}} $</p>
            </div>
            <div>
              <form action="{% url 'mycart:cart_add' product.pk %}" method="post">
                  {{cart_product_form}}
                  {% csrf_token %}
                  <div class="card-footer">
                      <input type="submit" value="add to cart" class="btn btn-primary" />
                  </div>              
              </form>
            </div>
          </div>
        </div>

		{% endif %}
      </div>
      <!-- /.row -->
{% endblock %}

shoponline/src/templates/mystore/readcookie.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>read cookie</title>
</head>
<body>
<h3>{{last_visit}}</h3>
</body>
</html>

shoponline/src/templates/mystore/registration.html
{% extends "mystore/base.html" %}

{% block body_block %}
<!-- Page Features -->
<div class="row text-center">
	 <!-- Page Features -->
      <div class="text-center">
      	{% if registered %}
      		<font color="blue">You registered successful</font>
      	{% else %}
      		<h3>Fill out form register</h3><br>
      		<form method="post" enctype="multipart/form-data">
      			<table>
      				{% for field in user_form %}
      					<tr>
      						<td>{{field.label}}</td>
      						<td>{{field}}</td>
      					</tr>
      				{% endfor %}
      				{% for field2 in profile_form %}
      					<tr>
      						<td>{{field2.label}}</td>
      						<td>{{field2}}</td>
      					</tr>
      				{% endfor %}
      				<tr>
      					<td colspan="2" align="center"><input type="submit" class="btn btn-primary" value="Register" /></td>
      				</tr>
      			</table>
      		{% csrf_token %}
      		</form>
      	{% endif %}
      </div>
      </div>
      <!-- /.row -->
{% endblock %}